import pygame as pg
#GAME OPTIONS / SETTINGS

# set title of the game
TITLE = "Tunnelit: The Best Game Ever Made"

# Useful Game Dimensions
TILESIZE = 50

# Set the Map width and all that
MAPWIDTH = 15
MAPHEIGHT = 11
# Set the Map margins
MAPHMARGIN = 35
MAPVMARGIN = 90

# set up the window width and height
WINDOWWIDTH = (MAPWIDTH*TILESIZE)+(MAPHMARGIN*2)
WINDOWHEIGHT = (MAPHEIGHT*TILESIZE)+MAPVMARGIN

# set up the colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
PURPLE = (102, 0, 204)
GREEN = (0, 255, 0)
DARKGREEN = (102, 204, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
DARKGREY = (128, 128, 128)
DARKBLUE = (0, 0, 51)
DARKORANGE = (139, 69, 0)
LIGHTBLUE = (0, 155, 155)

# set background images
BACKGROUND = pg.image.load("background.png")
INTRO = pg.image.load("intro.png")
P1WIN = pg.image.load("p1win.png")
P2WIN = pg.image.load("p2win.png")
BOTHLOSE = pg.image.load("bothL.png")

# set the font
FONT_NAME = 'Berlin Sans FB Demi'

# set up the frame rate
FRAMERATE = 60

# Player properties
PLAYERSPEED = 5

# Map Blocks
DBLOCK = 3
SIDEBLOCK = 2
MIDBLOCK = 1
GBLOCK = 0
# Map Tiles
tilemap = [[SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK],
           [SIDEBLOCK,GBLOCK,GBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,GBLOCK,GBLOCK,SIDEBLOCK],
           [SIDEBLOCK,GBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,GBLOCK,SIDEBLOCK],
           [SIDEBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,GBLOCK,DBLOCK,DBLOCK,DBLOCK,GBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,SIDEBLOCK],
           [SIDEBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,SIDEBLOCK],
           [SIDEBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,GBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,SIDEBLOCK],
           [SIDEBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,SIDEBLOCK],
           [SIDEBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,GBLOCK,DBLOCK,DBLOCK,DBLOCK,GBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,SIDEBLOCK],
           [SIDEBLOCK,GBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,DBLOCK,MIDBLOCK,GBLOCK,SIDEBLOCK],
           [SIDEBLOCK,GBLOCK,GBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,DBLOCK,GBLOCK,GBLOCK,SIDEBLOCK],
           [SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK,SIDEBLOCK]]
